
services:
  pyspark:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.3 # image name and tag
    container_name: sparkml_lab # custom container name 
    user: root
    command: start-notebook.sh --NotebookApp.token='' # removes the need for access token. Only do this for development work in your local machine
    ports:
      - "8888:8888" # Jupyter UI
      - "4040:4040" # Spark UI. Every new context is on an incremental port (4041, 4042, etc)
    volumes:
      - "./work/data:/home/jovyan/data"  # Data directory
      - "./notebooks:/home/jovyan/notebooks"  # Notebooks directory
    environment:
      - SPARK_WORKER_MEMORY=4g
